services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d yourdb"]
      interval: 5s
      timeout: 5s
      retries: 10
  nodejs:
    build: ./nodejs-app
    environment:
      PGUSER: youruser
      PGPASSWORD: yourpassword
      PGDATABASE: yourdb
      PGHOST: postgres
      PGPORT: 5432
      NODE_OPTIONS: "--max-old-space-size=4096"
    depends_on:
      - postgres
    working_dir: /usr/src/app
    command: ["node", "yourscript.js"]
volumes:
  pgdata:
